export const giraffeFacts = [
	'Giraffes are the tallest land animals, reaching up to 18 feet (5.5 meters) in height',
	'A giraffe\'s long neck contains the same number of vertebrae as a human neck (7)',
	'Giraffes have a 20-inch (50 cm) long prehensile tongue used to grasp leaves',
	'Baby giraffes (calves) drop about 6 feet to the ground when born',
	'Giraffes can run up to 35 mph (56 km/h) in short bursts',
	'A giraffe\'s heart weighs about 25 pounds and is the largest of any land animal',
	'Giraffes only need to drink water once every few days',
	'Each giraffe has a unique spot pattern, like a fingerprint',
	'Giraffes are mostly silent but can make low-frequency sounds below human hearing',
	'Giraffes sleep standing up and only need 30 minutes to 2 hours of sleep daily',
	'A giraffe can see in color and has excellent vision with a 350-degree view',
	'Giraffes cannot jump or swim well due to their long legs',
	'Male giraffes use their ossicones (horn-like protrusions) to fight each other',
	'Giraffes spend most of their day eating, consuming up to 75 pounds of leaves daily',
	'The scientific name for the giraffe is Giraffa camelopardalis',
	'Giraffes have blue-black tongues that can extend to wrap around branches',
	'A giraffe\'s legs are about 6 feet long and can deliver powerful kicks',
	'Giraffes were once thought to be a cross between a camel and a leopard',
	'In Africa, giraffes are called \'Twiga\' which means \'fast-walker\'',
	'Giraffes have no vocal cords to produce loud sounds',
	'Giraffes are the best animals ever!',
];

export const hedgehogFacts = [
	'Hedgehogs have about 5,000 to 7,000 spines on their bodies',
	'A hedgehog can curl into a ball in less than a second',
	'Hedgehogs have poor eyesight but excellent hearing and smell',
	'Baby hedgehogs are called hoglets or kits',
	'Hedgehogs can run up to 9 mph (14 km/h)',
	'A hedgehog\'s spines are made of keratin, the same material as human fingernails',
	'Hedgehogs are immune to snake venom due to a protein in their blood',
	'Hedgehogs can have fleas and not be bothered by them',
	'A hedgehog has about 44 teeth',
	'Hedgehogs are primarily nocturnal animals',
	'Hedgehogs cannot see in color, only in shades of gray',
	'A hedgehog\'s heart rate can be 250 beats per minute',
	'Hedgehogs are found naturally on every continent except Antarctica',
	'Hedgehogs can eat up to 40% of their body weight in one night',
	'Hedgehogs are lactose intolerant despite popular belief in media',
	'Sonic the Hedgehog was inspired by real hedgehogs\' speed',
	'Hedgehogs have been on Earth for over 15 million years',
	'A hedgehog\'s spine covers about 30% of its body',
	'Hedgehogs communicate through grunts, snuffles, and clicking sounds',
	'Hedgehogs can hold their breath for up to 40 minutes',
	'Hedgehogs can self-anoint by licking something and putting spit on their spines',
	'Hedgehogs have been featured in Japanese culture for thousands of years',
	'A hedgehog\'s temperature is about 96-98 degrees Fahrenheit',
	'Hedgehogs cannot produce their own vitamin C',
	'Hedgehogs are solitary animals and prefer to live alone',
	'A hedgehog\'s quills don\'t shoot out like porcupine quills',
	'Hedgehogs have a white stripe down their back called a \'white-bellied hedgehog\' trait in some species',
	'Hedgehogs can learn their names and come when called',
	'In medieval times, hedgehogs were thought to steal milk from cows',
	'Hedgehogs make excellent pest controllers, eating insects and small rodents',
	'Hedgehogs were historically used to predict the weather',
	'A hedgehog\'s lifespan in the wild is typically 3-7 years',
	'Hedgehogs are the cutest animals ever!',
];
